BodyTune/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BodyTune.Models;

namespace BodyTune.Controllers
{
    public class AssignmentsController : Controller
    {
        private DataModel db = new DataModel();

        // GET: Assignments
        public ActionResult Index()
        {
            var assignments = db.Assignments.Include(a => a.Exercise).Include(a => a.User);
            return View(assignments.ToList());
        }

        // GET: Assignments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assignment assignment = db.Assignments.Find(id);
            if (assignment == null)
            {
                return HttpNotFound();
            }
            return View(assignment);
        }

        // GET: Assignments/Create
        public ActionResult Create()
        {
            ViewBag.ExerciseId = new SelectList(db.Exercises, "ExerciseId", "ExerciseName");
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName");
            return View();
        }

        // POST: Assignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AssignmentId,StartDate,EndDate,Frequency,UserId,ExerciseId")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                db.Assignments.Add(assignment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ExerciseId = new SelectList(db.Exercises, "ExerciseId", "ExerciseName", assignment.ExerciseId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", assignment.UserId);
            return View(assignment);
        }

        // GET: Assignments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assignment assignment = db.Assignments.Find(id);
            if (assignment == null)
            {
                return HttpNotFound();
            }
            ViewBag.ExerciseId = new SelectList(db.Exercises, "ExerciseId", "ExerciseName", assignment.ExerciseId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", assignment.UserId);
            return View(assignment);
        }

        // POST: Assignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AssignmentId,StartDate,EndDate,Frequency,UserId,ExerciseId")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(assignment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ExerciseId = new SelectList(db.Exercises, "ExerciseId", "ExerciseName", assignment.ExerciseId);
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", assignment.UserId);
            return View(assignment);
        }

        // GET: Assignments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assignment assignment = db.Assignments.Find(id);
            if (assignment == null)
            {
                return HttpNotFound();
            }
            return View(assignment);
        }

        // POST: Assignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Assignment assignment = db.Assignments.Find(id);
            db.Assignments.Remove(assignment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BodyTune/Controllers/ExercisesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BodyTune.Models;

namespace BodyTune.Controllers
{
    public class ExercisesController : Controller
    {
        private DataModel db = new DataModel();

        // GET: Exercises
        public ActionResult Index()
        {
            var exercises = db.Exercises.Include(e => e.BodyPart);
            return View(exercises.ToList());
        }

        // GET: Exercises/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercise exercise = db.Exercises.Find(id);
            if (exercise == null)
            {
                return HttpNotFound();
            }
            return View(exercise);
        }

        // GET: Exercises/Create
        public ActionResult Create()
        {
            ViewBag.BodyPartId = new SelectList(db.BodyParts, "BodyPartId", "BodyPartName");
            return View();
        }

        // POST: Exercises/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ExerciseId,ExerciseName,ExerciseDescription,ExerciseImageUrl,BodyPartId")] Exercise exercise)
        {
            if (ModelState.IsValid)
            {
                db.Exercises.Add(exercise);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BodyPartId = new SelectList(db.BodyParts, "BodyPartId", "BodyPartName", exercise.BodyPartId);
            return View(exercise);
        }

        // GET: Exercises/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercise exercise = db.Exercises.Find(id);
            if (exercise == null)
            {
                return HttpNotFound();
            }
            ViewBag.BodyPartId = new SelectList(db.BodyParts, "BodyPartId", "BodyPartName", exercise.BodyPartId);
            return View(exercise);
        }

        // POST: Exercises/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ExerciseId,ExerciseName,ExerciseDescription,ExerciseImageUrl,BodyPartId")] Exercise exercise)
        {
            if (ModelState.IsValid)
            {
                db.Entry(exercise).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BodyPartId = new SelectList(db.BodyParts, "BodyPartId", "BodyPartName", exercise.BodyPartId);
            return View(exercise);
        }

        // GET: Exercises/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Exercise exercise = db.Exercises.Find(id);
            if (exercise == null)
            {
                return HttpNotFound();
            }
            return View(exercise);
        }

        // POST: Exercises/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Exercise exercise = db.Exercises.Find(id);
            db.Exercises.Remove(exercise);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BodyTune/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Body Tune</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <div class="navbar2 navbar-fixed-left">
        @Html.ActionLink("BodyTune", "Index", "Home", null, new { @class = "logoLink" })
        <div class="leftNavSections">
            <ul style="list-style: none;">
                <li><span class="leftNavHeadings">General</span></li>
                <li>@Html.ActionLink("About", "About", "Home", null, new { @class = "leftNavSubHeadings" })</li>
                <li>@Html.ActionLink("Mission", "Index", "Mission", null, new { @class = "leftNavSubHeadings" })</li>
                <li>@Html.ActionLink("Therapist", "Therapist", "Therapist", null, new { @class = "leftNavSubHeadings" })</li>
            </ul>
        </div>
        <div class="leftNavSections">
            <ul style="list-style: none;">
                <li><span class="leftNavHeadings">Exercise</span></li>
                <li>@Html.ActionLink("Library", "Index", "Exercises", null, new { @class = "leftNavSubHeadings" })</li>
                <li>@Html.ActionLink("Assigned", "Index", "Assignments", null, new { @class = "leftNavSubHeadings" })</li>
                <li>@Html.ActionLink("Favorites", "", "", new { @class = "leftNavSubHeadings" })</li>
                <li>@Html.ActionLink("History", "", "", new { @class = "leftNavSubHeadings" })</li>
            </ul>
        </div>
        <div class="leftNavSections">
            <ul style="list-style: none;">
                <li><span class="leftNavHeadings">My Account</span></li>
                <li>@Html.ActionLink("Personal Info", "", "", new { @class = "leftNavSubHeadings" })</li>
                <li>@Html.ActionLink("Edit", "", "", new { @class = "leftNavSubHeadings" })</li>
                <li>@Html.ActionLink("Change PW", "", "", new { @class = "leftNavSubHeadings" })</li>
            </ul>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Body Tune</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>